export _JAVA_AWT_WM_NONREPARENTING=1
exec feh --no-fehbg --bg-fill ~/sys/dots/etc/wallpaper/wallpaper.jpg &
barrierc -1 --disable-crypto --no-tray computer &
exec dunst &
while true; do status "with updates" && sleep 60; done &
exec picom --experimental-backends &
exec fusuma -d &
exec dwm
