.\" The fenze dots manpage
.\" Copyright © 2022 fenze <contact@fenze.dev>

.TH "" "1" "2022" "" "fenze bitwarden.sh Manual"

.SH NAME
.PP
bitwarden.sh - script that combines bitwarden
to dmenu allowing easy copy informations.

.SH DESCRIPTION
.PP
The intention behind the script is to simplify
the usage of the safe from desktop enviroment.

.SH OPTIONS
.PP
Basically script should take all commands available in dmenu and few more like:

\fBinstall\fP
  - Copies script to $PATH

\fBuninstall\fP
  - Removes script from $PATH

\fB--help\fP
  - Shows dmenu options

.SH SETUP
.PP
Before execute you must login to your account via bw login

.SH COPYRIGHT
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and any associated documentation files to modify, copy, merge,
publish, distribute and/or sublicense copies of this sotware for their own use.
This code does not come with any warranty.
