.\" The fenze dots manpage
.\" Copyright © 2022 fenze <contact@fenze.dev>

.TH "" "1" "2022" "" "Fenze Dotfiles Manual"

.SH DESCRIPTION
.PP
Configs of my enviroment that helps me improve my workflow and productivity.

.SH FILES
.PP
\fBbin/\fP
there you can find all scripts
that i use to improve workflow.

\fBetc/\fP
place for all configs.

\fBdocs/\fP
manpages for every file in this repository.

.SH COPYRIGHT
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and any associated documentation files to modify, copy, merge,
publish, distribute and/or sublicense copies of this sotware for their own use.
This code does not come with any warranty.
